<?php

return [
    "dublin" => [
        "id" => "dublin",
        "name" => "Biryani Spot & Chennai Dosa - Dublin",
        "short_name" => "Dublin",
        "address" => "4288 Dublin Blvd #111",
        "city" => "Dublin",
        "state" => "CA",
        "zip" => "94568",
        "phone" => "(925) 361-5317",
        "hours" => "11:00 AM - 10:00 PM Daily",
        "order_url" => "https://www.toasttab.com/biryani-spot-chennai-dosa-dublin/v3",
        "is_primary" => true,
    ],
    "milpitas" => [
        "id" => "milpitas",
        "name" => "Biryani Spot Chennai Dosa - Milpitas",
        "short_name" => "Milpitas",
        "address" => "380 South Main Street",
        "city" => "Milpitas",
        "state" => "CA",
        "zip" => "95035",
        "phone" => "(669) 264-7920",
        "hours" => "11:00 AM - 10:00 PM Daily",
        "order_url" => "https://www.toasttab.com/biryani-spot-chennai-dosa-milpitas/v3",
        "is_primary" => false,
    ],
    "livermore" => [
        "id" => "livermore",
        "name" => "Biryani Spot & Chennai Dosa - Livermore",
        "short_name" => "Livermore",
        "address" => "2050 Portola Avenue",
        "city" => "Livermore",
        "state" => "CA",
        "zip" => "94551",
        "phone" => "(669) 264-7920",
        "hours" => "11:00 AM - 10:00 PM Daily",
        "order_url" => "https://www.toasttab.com/biryani-spot-chennai-dosa-livermore/v3",
        "is_primary" => false,
    ],
    "concord" => [
        "id" => "concord",
        "name" => "Chennai Dosa Express - Concord",
        "short_name" => "Concord Express",
        "address" => "3540 Clayton Road",
        "city" => "Concord",
        "state" => "CA",
        "zip" => "94519",
        "phone" => "(925) 494-4470",
        "hours" => "11:00 AM - 9:30 PM Daily",
        "order_url" => "https://www.toasttab.com/chennai-dosa-express-concord/v3",
        "is_primary" => false,
    ],
];
